[package]
name = "hacktyper"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["derive"] }
crossterm = "0.29.0"
lazy_static = "1.5.0"
rand = "0.9.2"
regex = "1.12.2"
rodio = { version = "0.21.1", features = ["noise"] }
which = "8.0.0"
